from __future__ import annotations

from collections import deque
from dataclasses import dataclass

from mettafy.color_construction import PALETTE4, ConstructionState
from mettafy.kempe_traversal import KempeMove, all_component_moves, apply_kempe_move

StateKey = tuple[tuple[str, int], ...]


def state_key(state: ConstructionState) -> StateKey:
    """Canonical key for a coloring on one fixed graph carrier."""

    return tuple(sorted(state.coloring.items()))


@dataclass(frozen=True)
class ControlTransition:
    """One graph-derived control action on the coloration surface."""

    source: StateKey
    move: KempeMove
    target: StateKey


@dataclass(frozen=True)
class ImmediateControlCertificate:
    """One-step access certificate derived only from the current construction.

    The certificate contains no future target, path, or global reachability
    assumption.  When the focus has zero palette slack, ``move`` is an exact
    current Kempe-component control and ``after`` is the state obtained by that
    one control.  The next control, if needed, must be derived again from
    ``after``.
    """

    before: ConstructionState
    focus: str
    move: KempeMove
    after: ConstructionState

    @property
    def source_requires_control(self) -> bool:
        return not self.before.admissible_colors(self.focus)

    @property
    def same_carrier(self) -> bool:
        return dict(self.before.graph) == dict(self.after.graph)

    @property
    def same_committed_vertices(self) -> bool:
        return set(self.before.coloring) == set(self.after.coloring)

    @property
    def state_changes(self) -> bool:
        return state_key(self.before) != state_key(self.after)

    @property
    def valid(self) -> bool:
        if not self.source_requires_control:
            return False
        replayed = apply_kempe_move(self.before, self.move)
        return (
            self.same_carrier
            and self.same_committed_vertices
            and self.before.surface_genus == self.after.surface_genus == 0
            and self.before.committed_edges_valid
            and self.after.committed_edges_valid
            and self.state_changes
            and state_key(replayed) == state_key(self.after)
        )


def immediate_control_access(
    state: ConstructionState, focus: str
) -> ImmediateControlCertificate | None:
    """Construct one lawful control from the present state, with no lookahead.

    If ``A(focus)`` is already nonempty, no continuation control is required and
    ``None`` is returned.  Otherwise all four palette values occur among the
    committed neighbors of ``focus``.  Pick one such neighbor and any distinct
    palette value; the exact two-color component containing that neighbor exists
    by construction, and swapping it is a ledger-preserving current control.

    This establishes immediate access only.  It does not preselect or certify a
    later trajectory; any subsequent control is recomputed from the next state.
    """

    if focus not in state.graph:
        raise ValueError(f"unknown focus vertex {focus!r}")
    if focus in state.coloring:
        raise ValueError("focus must remain uncommitted during coloration control")
    if state.admissible_colors(focus):
        return None

    committed_neighbors = sorted(
        neighbor for neighbor in state.graph[focus] if neighbor in state.coloring
    )
    if not committed_neighbors:
        raise AssertionError("zero focus slack requires committed neighbors")

    seed = committed_neighbors[0]
    seed_color = state.coloring[seed]
    other_color = min(color for color in PALETTE4 if color != seed_color)
    move = KempeMove(seed=seed, other_color=other_color)
    after = apply_kempe_move(state, move)
    certificate = ImmediateControlCertificate(state, focus, move, after)
    if not certificate.valid:
        raise AssertionError("graph-derived immediate control failed its exact certificate")
    return certificate


@dataclass(frozen=True)
class ColorationControlSurface:
    """Finite navigation surface generated by exact graph-native controls.

    The carrier graph and genus-zero theorem species are not coordinates of this
    object: every node is a ConstructionState on the same graph.  The controls
    at each node are derived from the current two-color component structure.
    Proof-relevant control access is one-step/receding-horizon: after a step,
    controls are recomputed from the resulting state.
    """

    initial: ConstructionState
    focus: str

    def controls(self, state: ConstructionState) -> tuple[KempeMove, ...]:
        self._require_same_carrier(state)
        return all_component_moves(state)

    def immediate_access(
        self, state: ConstructionState
    ) -> ImmediateControlCertificate | None:
        self._require_same_carrier(state)
        return immediate_control_access(state, self.focus)

    def step(self, state: ConstructionState, move: KempeMove) -> ConstructionState:
        self._require_same_carrier(state)
        after = apply_kempe_move(state, move)
        self._require_same_carrier(after)
        return after

    def explore(
        self, max_depth: int
    ) -> tuple[dict[StateKey, ConstructionState], tuple[ControlTransition, ...]]:
        """Enumerate the exact control surface out to ``max_depth`` for audit."""

        if max_depth < 0:
            raise ValueError("max_depth must be non-negative")

        initial_key = state_key(self.initial)
        states = {initial_key: self.initial}
        depth = {initial_key: 0}
        queue: deque[StateKey] = deque([initial_key])
        transitions: list[ControlTransition] = []

        while queue:
            source_key = queue.popleft()
            source = states[source_key]
            source_depth = depth[source_key]
            if source_depth >= max_depth:
                continue

            for move in self.controls(source):
                target = self.step(source, move)
                target_key = state_key(target)
                transitions.append(ControlTransition(source_key, move, target_key))
                if target_key not in states:
                    states[target_key] = target
                    depth[target_key] = source_depth + 1
                    queue.append(target_key)

        return states, tuple(transitions)

    def shortest_focus_slack_path(
        self, max_depth: int
    ) -> tuple[KempeMove, ...] | None:
        """Diagnostic bounded search; not proof authority for control access."""

        if max_depth < 0:
            raise ValueError("max_depth must be non-negative")
        if self.initial.admissible_colors(self.focus):
            return ()

        initial_key = state_key(self.initial)
        states = {initial_key: self.initial}
        paths: dict[StateKey, tuple[KempeMove, ...]] = {initial_key: ()}
        queue: deque[StateKey] = deque([initial_key])

        while queue:
            source_key = queue.popleft()
            source = states[source_key]
            path = paths[source_key]
            if len(path) >= max_depth:
                continue

            for move in self.controls(source):
                target = self.step(source, move)
                target_key = state_key(target)
                candidate = path + (move,)
                if target.admissible_colors(self.focus):
                    return candidate
                if target_key not in states:
                    states[target_key] = target
                    paths[target_key] = candidate
                    queue.append(target_key)

        return None

    def ordered_pair_endpoints(
        self, first: KempeMove, second: KempeMove
    ) -> tuple[ConstructionState, ConstructionState]:
        """Apply the same two declared controls in both orders where legal."""

        first_then_second = self.step(self.step(self.initial, first), second)
        second_then_first = self.step(self.step(self.initial, second), first)
        return first_then_second, second_then_first

    def pair_commutes(self, first: KempeMove, second: KempeMove) -> bool:
        left, right = self.ordered_pair_endpoints(first, second)
        return state_key(left) == state_key(right)

    def _require_same_carrier(self, state: ConstructionState) -> None:
        if dict(state.graph) != dict(self.initial.graph):
            raise ValueError("control-surface traversal changed the graph carrier")
        if state.surface_genus != self.initial.surface_genus:
            raise ValueError("control-surface traversal changed the surface species")
        if set(state.coloring) != set(self.initial.coloring):
            raise ValueError("control-surface traversal changed committed vertex identity")
