from __future__ import annotations

from collections import deque
from dataclasses import dataclass

from mettafy.color_construction import ConstructionState
from mettafy.kempe_traversal import KempeMove, all_component_moves, apply_kempe_move

StateKey = tuple[tuple[str, int], ...]


def state_key(state: ConstructionState) -> StateKey:
    """Canonical key for a coloring on one fixed graph carrier."""

    return tuple(sorted(state.coloring.items()))


@dataclass(frozen=True)
class ControlTransition:
    """One graph-derived control action on the coloration surface."""

    source: StateKey
    move: KempeMove
    target: StateKey


@dataclass(frozen=True)
class ColorationControlSurface:
    """Finite-depth navigation surface generated by exact graph-native controls.

    The carrier graph and genus-zero theorem species are not coordinates of this
    object: every node is a ConstructionState on the same graph.  The controls
    at each node are derived from the current two-color component structure.
    This is a mechanical exploration object, not a global Four Color theorem.
    """

    initial: ConstructionState
    focus: str

    def controls(self, state: ConstructionState) -> tuple[KempeMove, ...]:
        self._require_same_carrier(state)
        return all_component_moves(state)

    def step(self, state: ConstructionState, move: KempeMove) -> ConstructionState:
        self._require_same_carrier(state)
        after = apply_kempe_move(state, move)
        self._require_same_carrier(after)
        return after

    def explore(
        self, max_depth: int
    ) -> tuple[dict[StateKey, ConstructionState], tuple[ControlTransition, ...]]:
        """Enumerate the exact control surface out to ``max_depth`` stages."""

        if max_depth < 0:
            raise ValueError("max_depth must be non-negative")

        initial_key = state_key(self.initial)
        states = {initial_key: self.initial}
        depth = {initial_key: 0}
        queue: deque[StateKey] = deque([initial_key])
        transitions: list[ControlTransition] = []

        while queue:
            source_key = queue.popleft()
            source = states[source_key]
            source_depth = depth[source_key]
            if source_depth >= max_depth:
                continue

            for move in self.controls(source):
                target = self.step(source, move)
                target_key = state_key(target)
                transitions.append(ControlTransition(source_key, move, target_key))
                if target_key not in states:
                    states[target_key] = target
                    depth[target_key] = source_depth + 1
                    queue.append(target_key)

        return states, tuple(transitions)

    def shortest_focus_slack_path(
        self, max_depth: int
    ) -> tuple[KempeMove, ...] | None:
        """Return a shortest exact path to positive ``A(focus)`` within a bound."""

        if max_depth < 0:
            raise ValueError("max_depth must be non-negative")
        if self.initial.admissible_colors(self.focus):
            return ()

        initial_key = state_key(self.initial)
        states = {initial_key: self.initial}
        paths: dict[StateKey, tuple[KempeMove, ...]] = {initial_key: ()}
        queue: deque[StateKey] = deque([initial_key])

        while queue:
            source_key = queue.popleft()
            source = states[source_key]
            path = paths[source_key]
            if len(path) >= max_depth:
                continue

            for move in self.controls(source):
                target = self.step(source, move)
                target_key = state_key(target)
                candidate = path + (move,)
                if target.admissible_colors(self.focus):
                    return candidate
                if target_key not in states:
                    states[target_key] = target
                    paths[target_key] = candidate
                    queue.append(target_key)

        return None

    def ordered_pair_endpoints(
        self, first: KempeMove, second: KempeMove
    ) -> tuple[ConstructionState, ConstructionState]:
        """Apply the same two declared controls in both orders where legal."""

        first_then_second = self.step(self.step(self.initial, first), second)
        second_then_first = self.step(self.step(self.initial, second), first)
        return first_then_second, second_then_first

    def pair_commutes(self, first: KempeMove, second: KempeMove) -> bool:
        left, right = self.ordered_pair_endpoints(first, second)
        return state_key(left) == state_key(right)

    def _require_same_carrier(self, state: ConstructionState) -> None:
        if dict(state.graph) != dict(self.initial.graph):
            raise ValueError("control-surface traversal changed the graph carrier")
        if state.surface_genus != self.initial.surface_genus:
            raise ValueError("control-surface traversal changed the surface species")
        if set(state.coloring) != set(self.initial.coloring):
            raise ValueError("control-surface traversal changed committed vertex identity")
