from __future__ import annotations

from .ir import ProvenanceEdge, Strategy


def _quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def emit_strategy_metta(
    strategies: list[Strategy],
    *,
    provenance_edges: list[ProvenanceEdge] | None = None,
) -> str:
    """Emit descriptive MeTTa atoms plus optional source-neutral provenance edges."""

    lines = ["; Generated by MeTTafy", "; Semantic strategy artifact"]
    for strategy in strategies:
        lines.append(f"(Strategy {_quote(strategy.id)} {strategy.kind.value})")
        lines.append(f"(Confidence {_quote(strategy.id)} {strategy.confidence:.2f})")
        for index, evidence in enumerate(strategy.evidence):
            evidence_id = f"{strategy.id}:evidence:{index}"
            lines.append(
                f"(Evidence {_quote(evidence_id)} {_quote(evidence.kind)} {_quote(evidence.detail)})"
            )
            lines.append(
                "(SourceSpan "
                f"{_quote(evidence_id)} {_quote(evidence.span.filename)} "
                f"{evidence.span.start_line} {evidence.span.end_line})"
            )
            lines.append(f"(Supports {_quote(evidence_id)} {_quote(strategy.id)})")

    for edge in provenance_edges or []:
        lines.append(
            f"(Provenance {_quote(edge.relation)} {_quote(edge.source_id)} {_quote(edge.target_id)})"
        )
    return "\n".join(lines) + "\n"
