from __future__ import annotations

from .ir import Strategy


def _quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def emit_strategy_metta(strategies: list[Strategy]) -> str:
    """Emit descriptive MeTTa atoms plus source-neutral provenance edges."""

    lines = ["; Generated by MeTTafy", "; Semantic strategy artifact"]
    for strategy in strategies:
        lines.append(f"(Strategy {_quote(strategy.id)} {strategy.kind.value})")
        lines.append(f"(Confidence {_quote(strategy.id)} {strategy.confidence:.2f})")
        for edge in strategy.provenance:
            lines.append(
                f"(Provenance {_quote(edge.relation)} {_quote(edge.source_id)} {_quote(edge.target_id)})"
            )
        for index, evidence in enumerate(strategy.evidence):
            evidence_id = f"{strategy.id}:evidence:{index}"
            lines.append(
                f"(Evidence {_quote(evidence_id)} {_quote(evidence.kind)} {_quote(evidence.detail)})"
            )
            lines.append(
                "(SourceSpan "
                f"{_quote(evidence_id)} {_quote(evidence.span.filename)} "
                f"{evidence.span.start_line} {evidence.span.end_line})"
            )
            lines.append(f"(Supports {_quote(evidence_id)} {_quote(strategy.id)})")
    return "\n".join(lines) + "\n"
