from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, TypeAlias

from mettafy import plane_parameterization as pp
from mettafy.color_construction import ConstructionState
from mettafy.plane_dual_control import (
    DualDomainNonzeroCertificate,
    DualDomainParameter,
    apply_dual_nonzero_parameter,
    canonical_edge,
)

ChoiceBit: TypeAlias = Literal[0, 1]
V4_TO_COLOR = {mode: color for color, mode in pp.COLOR_TO_V4.items()}


def palette_distance(left: pp.Color, right: pp.Color) -> int:
    """Discrete metric on the four terminal palette states."""

    if left not in pp.COLOR_TO_V4 or right not in pp.COLOR_TO_V4:
        raise ValueError("palette distance is defined only on Q4")
    return 0 if left == right else 1


def apply_palette_choice(color: pp.Color, mode: pp.V4, choice: ChoiceBit) -> pp.Color:
    """Apply one local binary choice: 0 stays put, 1 takes the unique V4 partner."""

    if color not in pp.COLOR_TO_V4:
        raise ValueError("color lies outside Q4")
    if mode not in pp.NONZERO_MODES:
        raise ValueError("choice direction must be a nonzero V4 mode")
    if choice not in (0, 1):
        raise ValueError("choice must be binary")
    if choice == 0:
        return color
    return V4_TO_COLOR[pp.v4_add(pp.COLOR_TO_V4[color], mode)]


def palette_choice_is_lipschitz_one(mode: pp.V4, choice: ChoiceBit) -> bool:
    """Exhaustively certify that one fixed local choice is an L=1 palette isometry."""

    if mode not in pp.NONZERO_MODES or choice not in (0, 1):
        return False
    colors = tuple(sorted(pp.COLOR_TO_V4))
    return all(
        palette_distance(
            apply_palette_choice(left, mode, choice),
            apply_palette_choice(right, mode, choice),
        )
        == palette_distance(left, right)
        for left in colors
        for right in colors
    )


def changed_partner(color: pp.Color, mode: pp.V4) -> pp.Color:
    """The unique other palette state reached by changing direction along ``mode``."""

    partner = apply_palette_choice(color, mode, 1)
    if partner == color:
        raise AssertionError("nonzero V4 translation unexpectedly fixed a palette state")
    return partner


def complementary_palette_opportunity(
    color: pp.Color,
    mode: pp.V4,
) -> tuple[pp.Color, pp.Color]:
    """The two untouched palette states sharing the same directional opportunity.

    A realized change ``q -> q + sigma`` has one pairwise consequence on the
    active two-state orbit.  The other two Q4 states form the complementary
    sigma-orbit.  They are not additional realized successors; they share one
    structural opportunity generated by the same direction.
    """

    if color not in pp.COLOR_TO_V4:
        raise ValueError("color lies outside Q4")
    if mode not in pp.NONZERO_MODES:
        raise ValueError("opportunity direction must be a nonzero V4 mode")
    active = {color, changed_partner(color, mode)}
    opportunity = tuple(sorted(set(pp.COLOR_TO_V4) - active))
    if len(opportunity) != 2:
        raise AssertionError("Q4 must split into two two-state sigma-orbits")
    left, right = opportunity
    if changed_partner(left, mode) != right:
        raise AssertionError("complementary palette states do not share one sigma-opportunity")
    return (left, right)


def edge_opportunity_modes(mode: pp.V4) -> tuple[pp.V4, pp.V4]:
    """The two nonzero edge modes sharing the opportunity induced by ``mode``.

    A proper crossed edge cannot already carry ``mode``.  Its current mode and
    its post-action mode are therefore exactly the other two nonzero V4 modes,
    exchanged by addition of ``mode``.
    """

    if mode not in pp.NONZERO_MODES:
        raise ValueError("opportunity direction must be a nonzero V4 mode")
    opportunity = tuple(sorted(candidate for candidate in pp.NONZERO_MODES if candidate != mode))
    if len(opportunity) != 2:
        raise AssertionError("one selected V4 direction must leave two opportunity modes")
    left, right = opportunity
    if pp.v4_add(left, mode) != right or pp.v4_add(right, mode) != left:
        raise AssertionError("the two opportunity modes must be exchanged by the selected direction")
    return (left, right)


@dataclass(frozen=True)
class DualDomainBinaryChoiceCertificate:
    """Pointwise stay/change-direction law underlying one exact dual domain action.

    For the chosen nonzero mode sigma, each committed vertex carries one bit
    chi(v): zero outside the translated domain and one inside it.  The realized
    coloring is

        c'(v) = c(v) + chi(v) sigma.

    Hence every committed edge uv obeys

        delta'(uv) = delta(uv) + (chi(u) xor chi(v)) sigma.

    A crossed cut edge is exactly an edge whose endpoint choices differ.  The
    retained dual parameter already certifies that no such edge has mode sigma,
    so the updated edge difference remains nonzero.
    """

    parameter: DualDomainParameter
    realization: DualDomainNonzeroCertificate

    @property
    def before(self) -> ConstructionState:
        return self.parameter.chart.base

    @property
    def after(self) -> ConstructionState:
        return self.realization.after

    @property
    def mode(self) -> pp.V4:
        return self.parameter.translation_mode

    @property
    def opportunity_modes(self) -> tuple[pp.V4, pp.V4]:
        return edge_opportunity_modes(self.mode)

    def choice(self, vertex: str) -> ChoiceBit:
        if vertex not in self.before.coloring:
            raise ValueError("choice is defined only for committed vertices")
        return 1 if vertex in self.parameter.translated_vertices else 0

    @property
    def choice_crossed_edges(self) -> frozenset[tuple[str, str]]:
        return frozenset(
            canonical_edge(vertex, neighbor)
            for vertex, neighbors in self.before.graph.items()
            for neighbor in neighbors
            if vertex in self.before.coloring
            and neighbor in self.before.coloring
            and vertex < neighbor
            and self.choice(vertex) != self.choice(neighbor)
        )

    @property
    def valid(self) -> bool:
        if not self.parameter.valid or not self.realization.valid:
            return False
        if self.realization.parameter is not self.parameter:
            return False
        if dict(self.before.graph) != dict(self.after.graph):
            return False
        if set(self.before.coloring) != set(self.after.coloring):
            return False
        if not palette_choice_is_lipschitz_one(self.mode, 0):
            return False
        if not palette_choice_is_lipschitz_one(self.mode, 1):
            return False

        expected_cut = frozenset(self.parameter.path.crossed_edges)
        if self.choice_crossed_edges != expected_cut:
            return False

        for vertex, before_color in self.before.coloring.items():
            if self.after.coloring[vertex] != apply_palette_choice(
                before_color,
                self.mode,
                self.choice(vertex),
            ):
                return False

        opportunity = frozenset(self.opportunity_modes)
        for vertex, neighbors in self.before.graph.items():
            if vertex not in self.before.coloring:
                continue
            for neighbor in neighbors:
                if neighbor not in self.before.coloring or vertex >= neighbor:
                    continue
                before_mode = pp.color_difference(
                    self.before.coloring[vertex],
                    self.before.coloring[neighbor],
                )
                after_mode = pp.color_difference(
                    self.after.coloring[vertex],
                    self.after.coloring[neighbor],
                )
                choices_differ = self.choice(vertex) ^ self.choice(neighbor)
                expected_mode = (
                    pp.v4_add(before_mode, self.mode)
                    if choices_differ
                    else before_mode
                )
                if after_mode != expected_mode:
                    return False
                if choices_differ:
                    if canonical_edge(vertex, neighbor) not in expected_cut:
                        return False
                    if before_mode == self.mode or after_mode == pp.ZERO:
                        return False
                    if frozenset({before_mode, after_mode}) != opportunity:
                        return False
                elif after_mode != before_mode:
                    return False

        return self.after.committed_edges_valid


def certify_dual_domain_binary_choice(
    parameter: DualDomainParameter,
) -> DualDomainBinaryChoiceCertificate:
    """Certify the exact pointwise binary-choice law for one chosen dual action."""

    if not parameter.valid:
        raise ValueError("a valid chosen dual parameter is required")
    certificate = DualDomainBinaryChoiceCertificate(
        parameter=parameter,
        realization=apply_dual_nonzero_parameter(parameter),
    )
    if not certificate.valid:
        raise AssertionError("dual-domain binary-choice law failed certification")
    return certificate
