import examples.four_color.MapMakerPareto
import examples.four_color.RedTeamComposition

/-
Copyright (c) 2026 Paul Carver Tiffany III.
Released under the MIT License; see LICENSE.

Proof-frontier reduction for the independent Four Color research lane.

NOVELTY / SCOPE
---------------
This file adds no new search procedure, completeness wrapper, geometric premise,
or authority mechanism. It composes already-banked results into the reduction
that motivates the MapMaker formulation:

  Do:Observe
    -> Imagine:Observe
    -> Imagine:Act*
    -> Do:Act

The complete Do/Imagine x Observe/Act product fixes phases 1, 2, and 4 by role.
All repeated strategic variation is therefore phase 3. For the four-color
palette, phase 3 lives on the minimal shared nonidentity V4 surface:

  total colors - 1 = 4 - 1 = 3.

Proper boundary contacts are differences in that same V4 surface; five boundary
locations do not create extra decision directions. Arbitrarily long sequential
imaginary traversal may revisit, cancel, branch before a residue is selected, or
compose consequences, but its retained V4 word has only four algebraic normal
forms: identity or one of the three nonzero directions. Any two distinct upward
states determine the unique third, and the pair plus forced third exhausts the
whole upward decision surface.

This is a proof-frontier reduction theorem, not a new Four Color theorem claim.
Implementation-specific routes (carrier geometry, projection mechanisms,
certification records) may still require their own witnesses, but they do not add
another strategic dimension beyond phase 3.
-/

namespace MeTTafy.FourColor

/-! ## 1. The operational product leaves only phase 3 repeatable -/

/--
Every operational cell is already uniquely represented by one MapMaker mode.
This is restated here only to make the dependency spine readable in one file.
-/
theorem proofFrontier_operational_product_complete
    (cell : OperationalCell) :
    ∃ mode : MapMakerMode,
      modeCell mode = cell ∧
        ∀ other : MapMakerMode, modeCell other = cell → other = mode :=
  MapMakerParetoComplete cell

/--
An ordered MapMaker residue has exactly one Do:Observe, exactly one
Imagine:Observe, any finite number of Imagine:Act steps, and exactly one Do:Act.
Hence the only repeatable part of the operational word is phase 3.
-/
theorem orderedProgram_only_repeats_step3
    (program : MapMakerProgram)
    (ordered : IsOrderedOperationalProgram program) :
    ∃ counterSteps : Nat,
      program =
        ([.overview, .localExpansion] ++
          List.replicate counterSteps .counterPlay) ++
        [.draw] := by
  rcases ordered with ⟨counterSteps, equal⟩
  refine ⟨counterSteps, ?_⟩
  simpa [orderedOperationalProgram, orderedPrecommitProgram] using equal

/-! ## 2. Phase 3 is exactly the three-direction V4 surface -/

/--
Any finite transferable consequence word from phase 3 reduces algebraically to
identity or one member of the explicit three-direction cover. No fourth
nonidentity direction can be generated by longer imagination.
-/
theorem step3Traversal_reduces_to_three_direction_surface
    (word : List ImaginaryDirection) :
    netDirection word = V4.zero ∨
      ∃ direction : ImaginaryDirection,
        direction ∈ ImaginaryDirection.all ∧
          netDirection word = direction.1 := by
  rcases imaginary_word_has_small_algebraic_normal_form word with
    zeroNet | nonzeroNet
  · exact Or.inl zeroNet
  · rcases nonzeroNet with ⟨direction, equal, _unique⟩
    exact Or.inr ⟨direction, ImaginaryDirection.mem_all direction, equal⟩

/--
Every proper boundary edge is itself one of the nonzero V4 directions. The five
boundary locations therefore reuse the same three-direction decision surface;
they are not five additional strategic dimensions.
-/
theorem properBoundary_lives_inside_step3_surface
    (boundary : Boundary5)
    (proper : ProperPentagon boundary) :
    ∃ d0 d1 d2 d3 d4 : ImaginaryDirection,
      edgeMode0 boundary = d0.1 ∧
      edgeMode1 boundary = d1.1 ∧
      edgeMode2 boundary = d2.1 ∧
      edgeMode3 boundary = d3.1 ∧
      edgeMode4 boundary = d4.1 := by
  rcases proper_boundary_edge_modes_are_nonzero boundary proper with
    ⟨h0, h1, h2, h3, h4⟩
  exact ⟨
    ⟨edgeMode0 boundary, h0⟩,
    ⟨edgeMode1 boundary, h1⟩,
    ⟨edgeMode2 boundary, h2⟩,
    ⟨edgeMode3 boundary, h3⟩,
    ⟨edgeMode4 boundary, h4⟩,
    rfl, rfl, rfl, rfl, rfl
  ⟩

/--
Fixing one reference leaves three upward states. Naming any two distinct upward
states determines the forced third, and those three exhaust every upward state.
This is the finite decision-completeness law used by phase 3.
-/
theorem step3_pair_forces_remaining_and_exhausts
    (reference left right : V4)
    (leftUp : UpwardFrom reference left)
    (rightUp : UpwardFrom reference right)
    (different : left ≠ right) :
    UpwardFrom reference (forcedThirdFrom reference left right) ∧
    forcedThirdFrom reference left right ≠ left ∧
    forcedThirdFrom reference left right ≠ right ∧
    ∀ state : V4,
      UpwardFrom reference state →
        state = left ∨
        state = right ∨
        state = forcedThirdFrom reference left right := by
  refine ⟨
    forcedThird_ne_reference reference left right leftUp rightUp different,
    forcedThird_ne_left reference left right leftUp rightUp different,
    forcedThird_ne_right reference left right leftUp rightUp different,
    ?_
  ⟩
  intro state stateUp
  exact upward_states_exhausted_by_pair_and_forcedThird
    reference left right state leftUp rightUp different stateUp

/--
Once those three upward states have acted, the existing void rule stops the local
phase-3 game. This is consequence exhaustion, not another completeness layer.
-/
theorem exhausted_step3_surface_stops
    (reference left right : V4)
    (leftUp : UpwardFrom reference left)
    (rightUp : UpwardFrom reference right)
    (different : left ≠ right)
    (acted available : V4 → Prop)
    (leftActed : acted left)
    (rightActed : acted right)
    (thirdActed : acted (forcedThirdFrom reference left right))
    (voidBlocks : VoidBlocksActed acted available) :
    UpwardGameStopped reference available :=
  all_three_upward_acted_and_void_blocked_stop_game
    reference left right leftUp rightUp different
    acted available leftActed rightActed thirdActed voidBlocks

/-! ## 3. One theorem spine: MapMaker downshifts the proof frontier to phase 3 -/

/--
The central reduction, with no new premise.

For any ordered MapMaker residue, any proper realized five-boundary, and any
finite retained phase-3 consequence word:

* phases 1, 2, and 4 have fixed operational roles and only phase 3 repeats;
* every boundary contact is already a member of the same nonzero V4 surface;
* arbitrary retained phase-3 traversal has no algebraic normal form outside
  identity or one of the three explicit directions;
* for every reference, any two distinct upward states plus their forced third
  exhaust every possible upward state.

Thus, inside the MapMaker operational ontology, the strategic proof frontier is
phase 3 on the three-direction shared surface. Carrier construction, projection,
and certified draw remain implementation/authority mechanisms around that
frontier rather than additional strategic dimensions.
-/
theorem mapMakerPareto_reduces_proof_frontier_to_step3
    (program : MapMakerProgram)
    (ordered : IsOrderedOperationalProgram program)
    (boundary : Boundary5)
    (proper : ProperPentagon boundary)
    (word : List ImaginaryDirection) :
    (∃ counterSteps : Nat,
      program =
        ([.overview, .localExpansion] ++
          List.replicate counterSteps .counterPlay) ++
        [.draw]) ∧
    (∃ d0 d1 d2 d3 d4 : ImaginaryDirection,
      edgeMode0 boundary = d0.1 ∧
      edgeMode1 boundary = d1.1 ∧
      edgeMode2 boundary = d2.1 ∧
      edgeMode3 boundary = d3.1 ∧
      edgeMode4 boundary = d4.1) ∧
    (netDirection word = V4.zero ∨
      ∃ direction : ImaginaryDirection,
        direction ∈ ImaginaryDirection.all ∧
          netDirection word = direction.1) ∧
    (∀ reference left right state : V4,
      UpwardFrom reference left →
      UpwardFrom reference right →
      left ≠ right →
      UpwardFrom reference state →
        state = left ∨
        state = right ∨
        state = forcedThirdFrom reference left right) := by
  refine ⟨
    orderedProgram_only_repeats_step3 program ordered,
    properBoundary_lives_inside_step3_surface boundary proper,
    step3Traversal_reduces_to_three_direction_surface word,
    ?_
  ⟩
  intro reference left right state leftUp rightUp different stateUp
  exact upward_states_exhausted_by_pair_and_forcedThird
    reference left right state leftUp rightUp different stateUp

end MeTTafy.FourColor
